# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: passenger-metrics 0.0.2 ruby lib

Gem::Specification.new do |s|
  s.name = "passenger-metrics"
  s.version = "0.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Nathan Woodhull"]
  s.date = "2016-03-09"
  s.description = "Get passenger metrics from passenger-status into the analytics tool of your choice."
  s.email = "nathan@gcontrolshiftlabs.com"
  s.executables = ["passenger-metrics-cloudwatch"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/_guard-core",
    "bin/guard",
    "bin/passenger-metrics-cloudwatch",
    "lib/passenger-metrics.rb",
    "lib/passenger-metrics/cloudwatch.rb",
    "lib/passenger-metrics/metrics/base.rb",
    "lib/passenger-metrics/metrics/process_count.rb",
    "lib/passenger-metrics/metrics/queue_length.rb",
    "lib/passenger-metrics/status.rb",
    "passenger-metrics.gemspec",
    "spec/fixtures/status.xml",
    "spec/passenger-metrics/cloudwatch_spec.rb",
    "spec/passenger-metrics/metrics/process_count_spec.rb",
    "spec/passenger-metrics/status_spec.rb",
    "spec/passenger_metrics_spec.rb",
    "spec/spec_helper.rb",
    "spec/status_spec.rb"
  ]
  s.homepage = "http://github.com/controlshift/passenger-metrics"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.8"
  s.summary = "ruby interface to passenger-status"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<crack>, [">= 0"])
      s.add_runtime_dependency(%q<aws-sdk>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<guard>, [">= 0"])
      s.add_development_dependency(%q<guard-rspec>, [">= 0"])
      s.add_development_dependency(%q<byebug>, [">= 0"])
    else
      s.add_dependency(%q<crack>, [">= 0"])
      s.add_dependency(%q<aws-sdk>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<guard>, [">= 0"])
      s.add_dependency(%q<guard-rspec>, [">= 0"])
      s.add_dependency(%q<byebug>, [">= 0"])
    end
  else
    s.add_dependency(%q<crack>, [">= 0"])
    s.add_dependency(%q<aws-sdk>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<guard>, [">= 0"])
    s.add_dependency(%q<guard-rspec>, [">= 0"])
    s.add_dependency(%q<byebug>, [">= 0"])
  end
end

